"""
Hybrid Gemini + Computer Vision approach
Uses Gemini to understand image content and guide search, then uses CV for precise detection
"""

import time
import os
import sys
import cv2
import numpy as np
from typing import List, Tuple, Optional
from google import genai
from PIL import Image
from common_utils import draw_bounding_boxes, format_bounding_boxes
from dotenv import load_dotenv

# Load environment variables
load_dotenv()
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
if not GEMINI_API_KEY:
    print("Error: GEMINI_API_KEY not found in .env file.")
    raise ValueError("Missing GEMINI_API_KEY")

_gemini_client = None

# Fallback query expansions when API is unavailable
QUERY_EXPANSIONS = {
    'settings': ['gear icon', 'cogwheel', 'cog icon', 'preferences icon', 'configuration icon'],
    'account': ['user icon', 'profile icon', 'person icon', 'avatar', 'account circle'],
    'home': ['house icon', 'home icon', 'building', 'homepage icon'],
    'search': ['magnifying glass', 'search icon', 'lens icon', 'zoom icon'],
    'menu': ['hamburger menu', 'three lines', 'navigation icon', 'menu bars'],
    'close': ['x icon', 'close icon', 'cancel icon', 'cross icon'],
    'delete': ['trash icon', 'bin icon', 'garbage icon', 'delete icon'],
    'edit': ['pencil icon', 'pen icon', 'edit icon', 'modify icon'],
    'save': ['disk icon', 'floppy icon', 'save icon', 'download icon'],
    'share': ['share icon', 'arrow icon', 'export icon', 'send icon'],
    'like': ['heart icon', 'thumbs up', 'favorite icon', 'star icon'],
    'bookmark': ['bookmark icon', 'flag icon', 'ribbon icon', 'save icon'],
    'notification': ['bell icon', 'alert icon', 'notification icon'],
    'mail': ['envelope icon', 'email icon', 'message icon', 'mail icon'],
    'phone': ['phone icon', 'call icon', 'telephone icon'],
    'location': ['pin icon', 'map marker', 'location icon', 'place icon'],
    'calendar': ['calendar icon', 'date icon', 'schedule icon'],
    'clock': ['clock icon', 'time icon', 'watch icon'],
    'lock': ['lock icon', 'padlock', 'security icon', 'key icon'],
    'unlock': ['unlock icon', 'open lock', 'unlocked icon'],
}


def expand_query(query: str) -> List[str]:
    """
    Expand the user's query into multiple visual descriptions using Gemini AI.
    E.g., "settings" → ["gear icon", "cogwheel", "settings icon", "cog"]
    Falls back to hardcoded dictionary if API is unavailable.
    """
    global _gemini_client
    
    if _gemini_client is None:
        _gemini_client = genai.Client(api_key=GEMINI_API_KEY)
    
    query_lower = query.lower()
    
    # First, try to generate expansions using Gemini AI
    prompt = f"""You are a UI/UX expert. A user is searching for an icon or UI element described as: "{query}"

Generate a list of 5-8 visual descriptions or synonyms that could represent this element in an icon set.

Examples:
Input: "settings"
Output: gear icon, cogwheel, cog icon, settings gear, preferences icon

Input: "account" 
Output: user icon, profile icon, person icon, avatar, account circle, user silhouette

Input: "home"
Output: house icon, home icon, building, homepage, dwelling

Input: "adjust volume"
Output: speaker icon, volume icon, sound icon, audio icon, mute icon

Now generate alternatives for: "{query}"

Return ONLY the comma-separated list, no explanations or extra text."""

    try:
        response = _gemini_client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt
        )
        
        if not response or not response.text:
            raise ValueError("Empty response from Gemini")
        
        # Parse the response
        alternatives = [w.strip().lower() for w in response.text.split(',')]
        alternatives = [w for w in alternatives if w]  # Remove empty
        
        # Add original query at the start
        result = [query_lower] + [alt for alt in alternatives if alt != query_lower]
        
        print(f"\n{'='*60}")
        print(f"Query Expansion: '{query}' (generated by Gemini AI)")
        print(f"Searching for: {', '.join(result[:6])}")
        if len(result) > 6:
            print(f"             + {len(result)-6} more variations...")
        print(f"{'='*60}\n")
        
        return result[:8]  # Limit to 8 variations to avoid too many API calls
        
    except Exception as e:
        print(f"[Query Expansion] Gemini API unavailable: {str(e)[:100]}")
        
        # Fall back to hardcoded dictionary
        if query_lower in QUERY_EXPANSIONS:
            result = [query_lower] + QUERY_EXPANSIONS[query_lower]
            print(f"[Query Expansion] Using built-in dictionary fallback for '{query}'")
            print(f"[Query Expansion] Searching for: {', '.join(result[:6])}")
            if len(result) > 6:
                print(f"                 + {len(result)-6} more variations...")
            print()
            return result
        else:
            print(f"[Query Expansion] No fallback available, using original query only")
            print()
            return [query_lower]


def get_gemini_description(image_path: str, element_description: str) -> dict:
    """
    Use Gemini to understand the image and describe what elements exist.
    Returns semantic understanding rather than precise coordinates.
    """
    global _gemini_client
    
    if _gemini_client is None:
        _gemini_client = genai.Client(api_key=GEMINI_API_KEY)
    
    image = Image.open(image_path)
    width, height = image.size
    
    prompt = f"""Analyze this {width}x{height} pixel image.

Question: Where is/are the "{element_description}" in this image?

Describe:
1. How many instances do you see?
2. What does each one look like visually (shape, color, style)?
3. If this is a GRID of icons/elements:
   - Count total rows and columns
   - For each match, specify: row number (1=top), column number (1=left)
   - Example: "row 3, column 5"
4. If NOT a grid layout:
   - Use 3x3 regions: top-left, top-center, top-right, middle-left, middle-center, middle-right, bottom-left, bottom-center, bottom-right
5. Estimated size: tiny (<30px), small (30-60px), medium (60-150px), large (>150px)
6. Any distinctive visual features to help identify it

Be specific and accurate. If you don't see any, say "None found"."""

    try:
        response = _gemini_client.models.generate_content(
            model='gemini-2.5-flash',
            contents=[image, prompt]
        )
        
        print("\n" + "="*60)
        print("Gemini's Description:")
        print("="*60)
        print(response.text)
        print("="*60)
        
        return {
            'description': response.text,
            'image_size': (width, height)
        }
    except Exception as e:
        print(f"Error calling Gemini: {e}")
        return {'description': '', 'image_size': (width, height)}


def detect_with_blob_detection(image_path: str, region_hint: dict) -> List[Tuple[int, int, int, int]]:
    """
    Use OpenCV blob detection to find icon-like objects.
    Uses Gemini's hints to focus search.
    """
    image = cv2.imread(image_path)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    height, width = image.shape[:2]
    
    # Invert if icons are dark on light background
    _, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY_INV)
    
    # Find contours (potential icons)
    contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    
    bounding_boxes = []
    
    for contour in contours:
        x, y, w, h = cv2.boundingRect(contour)
        area = w * h
        aspect_ratio = w / h if h > 0 else 0
        
        # Filter for icon-like objects:
        # - Reasonable size (15-100 pixels)
        # - Roughly square (aspect ratio 0.5 to 2.0)
        # - Not too small or too large
        if (15 <= w <= 100 and 15 <= h <= 100 and 
            0.5 <= aspect_ratio <= 2.0 and
            100 <= area <= 10000):
            bounding_boxes.append((x, y, x + w, y + h))
    
    print(f"\n[CV Detection] Found {len(bounding_boxes)} icon-like objects")
    return bounding_boxes


def filter_boxes_by_description(boxes: List[Tuple[int, int, int, int]], 
                                description: str, 
                                image_size: Tuple[int, int]) -> List[Tuple[int, int, int, int]]:
    """
    Filter detected boxes based on Gemini's description.
    """
    if not description or 'none found' in description.lower():
        return []
    
    width, height = image_size
    filtered = []
    desc_lower = description.lower()
    
    # Try to extract grid position (e.g., "row 5, column 1" or "row 3" or "column 2")
    import re
    row_match = re.search(r'row\s+(\d+)', desc_lower)
    col_match = re.search(r'column\s+(\d+)', desc_lower)
    
    if row_match or col_match:
        print(f"[Grid Detection] Found grid position in description")
        
        # Try to determine grid dimensions
        rows_match = re.search(r'(\d+)\s+rows', desc_lower)
        cols_match = re.search(r'(\d+)\s+columns', desc_lower)
        
        # Default assumptions for icon grids
        total_rows = int(rows_match.group(1)) if rows_match else 5
        total_cols = int(cols_match.group(1)) if cols_match else 8
        
        target_row = int(row_match.group(1)) if row_match else None
        target_col = int(col_match.group(1)) if col_match else None
        
        print(f"[Grid] Estimated grid: {total_rows} rows x {total_cols} cols")
        print(f"[Grid] Target position: row {target_row}, column {target_col}")
        
        # Calculate cell dimensions
        cell_width = width / total_cols
        cell_height = height / total_rows
        
        # For each detected box, check if it falls in the target grid cell
        for x1, y1, x2, y2 in boxes:
            box_center_x = (x1 + x2) / 2
            box_center_y = (y1 + y2) / 2
            
            box_row = int(box_center_y // cell_height) + 1  # 1-indexed
            box_col = int(box_center_x // cell_width) + 1   # 1-indexed
            
            # Check if thisbox matches the target position
            row_match_flag = (target_row is None or box_row == target_row)
            col_match_flag = (target_col is None or box_col == target_col)
            
            if row_match_flag and col_match_flag:
                print(f"[Grid] Box at ({x1}, {y1})-({x2}, {y2}) matches: grid position ({box_row}, {box_col})")
                filtered.append((x1, y1, x2, y2))
        
        if filtered:
            return filtered
    
    # Fall back to 3x3 region filtering
    print(f"[Fallback] Using 3x3 region filtering")
    location_keywords = {
        'top': (0, 0.33),
        'middle': (0.33, 0.66),
        'bottom': (0.66, 1.0),
        'left': (0, 0.33),
        'center': (0.33, 0.66),
        'right': (0.66, 1.0),
    }
    
    vertical_range = (0, 1.0)
    horizontal_range = (0, 1.0)
    
    for keyword, (start, end) in location_keywords.items():
        if keyword in desc_lower:
            if keyword in ['top', 'middle', 'bottom']:
                vertical_range = (start, end)
            else:
                horizontal_range = (start, end)
    
    for x1, y1, x2, y2 in boxes:
        center_x = (x1 + x2) / 2
        center_y = (y1 + y2) / 2
        norm_x = center_x / width
        norm_y = center_y / height
        
        if (vertical_range[0] <= norm_y <= vertical_range[1] and
            horizontal_range[0] <= norm_x <= horizontal_range[1]):
            filtered.append((x1, y1, x2, y2))
    
    print(f"[Filtering] {len(filtered)} boxes match description")
    return filtered if filtered else boxes[:5]  # Return up to 5 if no matches


def find_elements_hybrid(image_path: str, element_description: str) -> Tuple[List[Tuple[int, int, int, int]], float]:
    """
    Hybrid approach: Use Gemini for understanding, CV for precise detection.
    """
    start_time = time.time()
    
    print(f"\n[HYBRID DETECTION] Looking for: '{element_description}'")
    
    # Step 0: Expand query to multiple visual descriptions
    print(f"\n[STEP 0/4] Expanding query to visual descriptions...")
    expanded_queries = expand_query(element_description)
    
    all_detections = []
    
    # Try detection with each expanded query
    for i, query_variant in enumerate(expanded_queries, 1):
        print(f"\n[STEP {i}/4] Trying variant: '{query_variant}'")
        print(f"  └─ Getting semantic understanding from Gemini...")
        
        # Step 1: Get semantic understanding from Gemini
        gemini_info = get_gemini_description(image_path, query_variant)
        
        # Check if Gemini found anything
        if 'none found' in gemini_info['description'].lower():
            print(f"  └─ Gemini found nothing for '{query_variant}', skipping...")
            continue
        
        # Step 2: Use computer vision to detect all icon-like objects (only once)
        if i == 1:  # Only detect once, reuse for other queries
            print(f"  └─ Using computer vision to detect objects...")
            all_boxes = detect_with_blob_detection(image_path, gemini_info)
        
        # Step 3: Filter based on Gemini's description
        print(f"  └─ Filtering based on semantic understanding...")
        filtered_boxes = filter_boxes_by_description(
            all_boxes, 
            gemini_info['description'],
            gemini_info['image_size']
        )
        
        if filtered_boxes:
            all_detections.extend(filtered_boxes)
            print(f"  └─ ✓ Found {len(filtered_boxes)} match(es) for '{query_variant}'")
            break  # Stop if we found something
        else:
            print(f"  └─ ✗ No matches for '{query_variant}'")
    
    # Deduplicate detections (remove boxes that are very close to each other)
    unique_detections = []
    for box in all_detections:
        is_duplicate = False
        x1, y1, x2, y2 = box
        center_x = (x1 + x2) / 2
        center_y = (y1 + y2) / 2
        
        for existing_box in unique_detections:
            ex1, ey1, ex2, ey2 = existing_box
            ex_center_x = (ex1 + ex2) / 2
            ex_center_y = (ey1 + ey2) / 2
            
            # If centers are within 20 pixels, consider it duplicate
            distance = ((center_x - ex_center_x)**2 + (center_y - ex_center_y)**2)**0.5
            if distance < 20:
                is_duplicate = True
                break
        
        if not is_duplicate:
            unique_detections.append(box)
    
    inference_time = time.time() - start_time
    return unique_detections, inference_time


def process_image(image_path: str, prompt: str, output_path: str):
    """Process image using hybrid detection."""
    bounding_boxes, inference_time = find_elements_hybrid(image_path, prompt)
    
    print(f"\n{'='*60}")
    print(f"FINAL RESULT: Found {len(bounding_boxes)} matches in {inference_time:.3f}s")
    print(format_bounding_boxes(bounding_boxes))
    print(f"{'='*60}")
    
    draw_bounding_boxes(image_path, bounding_boxes, prompt, inference_time, output_path)
    
    return bounding_boxes, inference_time


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python gemini_hybrid_test.py <image_path> <element_description> [output_path]")
        print("\nThis hybrid approach:")
        print("  1. Uses Gemini to understand what's in the image")
        print("  2. Uses computer vision to precisely detect icon locations")
        print("  3. Combines both for accurate results")
        print("\nExamples:")
        print("  python gemini_hybrid_test.py input-images/input-icons.png \"gear icon\"")
        print("  python gemini_hybrid_test.py input-images/input-youtube.png \"profile picture\"")
        sys.exit(1)
    
    image_path = sys.argv[1]
    element_description = sys.argv[2]
    
    if len(sys.argv) > 3:
        output_path = sys.argv[3]
    else:
        base_name = os.path.splitext(os.path.basename(image_path))[0]
        if base_name.startswith("input-"):
            base_name = base_name[6:]
        output_path = f"output-images/output-{base_name}.png"
    
    process_image(image_path, element_description, output_path)
